### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by abresler** [jangorecki/Rbitcoin#12]
Trying to recreate the toy example from R-bloggers 
http://www.r-bloggers.com/querying-the-bitcoin-blockchain-with-r/ 

and I am encountering this error on trying to use the blockchain.api.process function
```r
seed <- '1NfRMkhm5vjizzqkp2Qb28N7geRQCa4XqC'
genesis <- '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
singleaddress <- blockchain.api.query(method = 'Single Address', bitcoin_address = seed, limit=100)

Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5)
```

**Comment by jangorecki** [comment]
Please read this single line in the documentation: [Rbitcoin.Rd#L26](https://github.com/jangorecki/Rbitcoin/blob/master/man/Rbitcoin.Rd#L26).
Your CA is located in `system.file("CurlSSL","cacert.pem",package="RCurl")`, you can get the recent one from the [curl.haxx.se](http://curl.haxx.se/docs/caextract.html) and simply replace it.
If you believe CA file is up to date you can confirm that RCurl package works by:
```r
library(RCurl)
res = getURL("https://blockchain.info/address/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa?format=json")
str(res)
# chr "{\n\t\"hash160\":\"62e907b1..... 
```
I assume if you manage to work RCurl then the Rbitcoin should work too.
If the RCurl works and Rbitcoin still does not works please let me know, otherwise close issue.

**Comment by abresler** [comment]
Worked!!  Thank you so much for the quick response.  By way of context I am trying to show some less than tech savvy people the value of a blockchain and found your amazing package to do it in the context of bitcoin.  Blockchain is at the center of a business venture I am toying with and if it happens I can't wait to share but thank you for your work on this package; can't wait to use it to highlight the power of APIs and the block chain :)

**Comment by abresler** [comment]
When I try your test it works but I still can't get the function to work -- here is the test you outlined:
library(RCurl);library(magrittr)
getURL("https://blockchain.info/address/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa?format=json") %>% str
 chr "{\n\t\"hash160\":\"62e907b15cbf27d5425399ebf6f0fb50ebb88f18\",\n\t\"address\":\"1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa\",\n\t\"n_tx"| __truncated__

but still 
seed <-
+ '1NfRMkhm5vjizzqkp2Qb28N7geRQCa4XqC'
> genesis <-
+ '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
> singleaddress <-
+ seed %>%
+ blockchain.api.query(method = 'Single Address', bitcoin_address = ., limit=100)
Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5) 

any further thoughts would be appreciated

**Comment by jangorecki** [comment]
Learning about bitcoin/blockchain can be tough, good luck :) yet my package is mostly about market API unification and/or simplifying the call. It is a tiny part of that technology. You may want to look for some better, more theoretical works which can highlight some nice aspects of blockchain. Rbitcoin is quite practically focused.
Regarding you second post, can you format your code?

**Comment by abresler** [comment]
```{r}
library(Rbitcoin) #an R package to interface with bitcoin blockchain
library(magrittr)
seed <-
	'1NfRMkhm5vjizzqkp2Qb28N7geRQCa4XqC'
genesis <-
	'1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
'1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
singleaddress <-
	seed %>%
	blockchain.api.query(method = 'Single Address', bitcoin_address = ., limit=100)
```

**Comment by jangorecki** [comment]
Assuming the error message is still related to SSL, I think your R still uses old CA file.
See [this](https://github.com/jangorecki/Rbitcoin/blob/master/man/Rbitcoin.Rd#L50) block of example options for RCurl. Be sure to set `cainfo` to new CA file. R has multiple libraries available (user, global, etc.) so it is possible your session is using different version then the one you updated.

**Comment by abresler** [comment]
Worst case how do I turn of SSL -- I think you maybe right on the multiple cacerts but I did change the cacert referenced for rCurl.

**Comment by jangorecki** [comment]
From the mentioned RCurl options update both `O$ssl.*` to `FALSE`, you can skip `cainfo`. Also you may set `O$verbose <- TRUE` which will produce curl message, I found it very useful in debugging API connections.

**Comment by abresler** [comment]
Oyee now this:

```{r}
library(RCurl)
O <- getOption("RCurlOptions")
O$ssl.verifyhost <- as.integer(2)
O$ssl.verifypeer <- FALSE
O$cainfo <- system.file("CurlSSL","cacert.pem",package="RCurl")
O$verbose <- TRUE
options("RCurlOptions" = O)

library(Rbitcoin) #an R package to interface with bitcoin blockchain

seed <-
	'1NfRMkhm5vjizzqkp2Qb28N7geRQCa4XqC'
genesis <-
	'1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'

singleaddress <-
	blockchain.api.query(method = 'Single Address', bitcoin_address = seed, limit=100,)

```
Error in blockchain.api.query(method = "Single Address", bitcoin_address = seed,  : 
  argument is missing, with no default

**Comment by jangorecki** [comment]
remove last `,` after the `limit=100` :)

**Comment by abresler** [comment]
* Hostname was NOT found in DNS cache
*   Trying 190.93.243.195...
* Connected to blockchain.info (190.93.243.195) port 443 (#0)
* SSL: CA certificate set, but certificate verification is disabled
* Closing connection 0
Error in function (type, msg, asError = TRUE)  : 
  SSL: CA certificate set, but certificate verification is disabled -- will keep playing around but you are able to recreate the toy example?

**Comment by abresler** [comment]
Think this worked! 

```{r}
opts <- list(
	capath = system.file("CurlSSL", "cacert.pem", package = "RCurl"), 
	ssl.verifypeer = FALSE);
```

**Comment by jangorecki** [comment]
Good it works now.
BTW. you can set `ssl.verifyhost` to `FALSE` also, it is `as.integer(2)` by default due to curl library update, described here: https://github.com/omegahat/RCurl/issues/12
If you find your issue resolved you can close the issue.
