### ISSUE TITLE
Allow user to add currency pairs to api dictionary

### ISSUE THREAD

**Issue by rexmacey** [jangorecki/Rbitcoin#17]
I'd like users to be able to either add currency pairs to the api dictionary or for the market.api.process to attempt pairs that are not in the dictionary.  For example, it appears to me that Kraken supports Bitcoin Cash (BCH) to USD but this is not in the dictionary (0.9.7).

It seems that markets support new currency pairs all the time and that it would be difficult for the package developer to keep up.   Thus having users be able to add pairs would help as would having the system attempt to add pairs on the fly.  

The documentation says 

> This dictionary can be edited/extended by user for new markets.

However, I can neither find documentation explaining how to edit the dictionary nor figure it out.  Perhaps all that is needed is more documentation.

**Comment by jangorecki** [comment]
There is no documentation about that process but you can easily see what is needed by looking at this commit https://gitlab.com/jangorecki/Rbitcoin/commit/0a232c25a05641f9d141c78eae6b7429e776cd0d
You should be able to create any currency pair (and currency type) on the fly using options, so no changes to code are required. Although I cannot guarantee that, I haven't been looking at that package for a long time.
