### ISSUE TITLE
fetch blockchain info from local bitcoind

### ISSUE THREAD

**Issue by jangorecki** [jangorecki/Rbitcoin#8]
Cannot use [JSON-RPC](https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)) due to http://bitcoin.stackexchange.com/a/23708/4822
Possibility interact with [leveldb](https://github.com/google/leveldb) internal blockchain's database

**Comment by micahstubbs** [comment]
@jangorecki are there other methods to fetch Blockchain info from the local bitcoind that look promising?

**Comment by jangorecki** [comment]
The most promising I've seen is: https://github.com/znort987/blockparser

**Comment by micahstubbs** [comment]
oh good!  thanks for the expert opinion @jangorecki :-)

**Comment by mpiccirilli** [comment]
Last I checked the znort parser didn't pick up p2sh transactions, which has become more and more popular.  You can see the p2sh volume/transactions here:  http://p2sh.info/p2sh.

This other [parser](https://code.google.com/p/blockchain/) will pick up p2sh transactions, but the output is only in aggregates (daily, monthly, yearly), so the C++ code needs to be modified a bit.

**Comment by jangorecki** [comment]
another option can be [minium/bitcoin-api-cpp](https://github.com/minium/bitcoin-api-cpp)

**Comment by jangorecki** [comment]
This is already handled by my other package [rbitcoind](https://github.com/jangorecki/rbitcoind) which is focused on bitcoin and blockchain, not on exchanges. It uses json-rpc (httr, jsonlite) so it will not be as fast as mentioned parsers. I will include test, script or vignette on reading blockchain into sqlite (or some nosql?) so only initial read will be slow. Closing issue here.
